# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 一言堂
email: yisha7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  朝闻道，夕死可矣。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yisha7.me" # the base hostname & protocol for your site
twitter_username: yisha7
github_username:  yisha7
permalink: none
# Build settings
markdown: kramdown
port: 8080
