# Site Info
title: "一言堂 - 念念不忘，必有回响"
baseurl: ''
weburl: 'http://yifeitao.com'
author: 'yifeitao'
logo: '/logo.jpg'

# Site configurations
plugins:
  - jekyll-paginate
  - jekyll-feed
markdown: kramdown

excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 10
paginate_path: '/page:num/'
permalink: '/:year//:month/:title'

# Navigation (2nd level links supported)
nav:
  Find Article:
    - '/'
    - { Archive: '/archive/' }
    - { Categories: '/categories/' }
    - { Tags: '/tags/' }
    - { Search: '/search/' }
  Find Me:
    - '/about/'
    - { About: '/about/' }
    - { Github: 'https://github.com/yifeitao'}
    - { Email: 'mailto:yifeitao@gmail.com'}
    - { Douban: 'https://www.douban.com/people/yisha7/'}
  Learning Notes: 
    - 'https://learn.yifeitao.com'

# Add your friend-links
# friends:
#   A: 'link_A'
#   B: 'link_B'

# Relative path compatibility (JS hack, experimental and buggy feature)
# relative_path: true

# Where are tags and categories displayed
disqus_shortname: yifeitao
tag_page: '/tags/'
category_page: '/categories/'
google_analytics: UA-98784328-1

# reveal.js slide template
reveal_path: https://cdn.bootcss.com/reveal.js/3.4.1/

# additional message in sidebar
addition: '</br>朝闻道 夕死可矣'
