# Site Info
title: "一言堂 - 念念不忘，必有回响"
baseurl: ''
weburl: 'https://yifeitao.com'
author: 'yifeitao'
logo: '/assets/images/logo.jpg'

# Site configurations
plugins:
  - jekyll-paginate
  - jekyll-feed
markdown: kramdown

excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 10
paginate_path: '/page:num/'
permalink: '/:year//:month/:title'

# Navigation (2nd level links supported)
nav:
  一言堂:
    - '/'
    - { 推荐: '/recommend/' }
    - { 归档: '/archive/' }
    - { 分类: '/categories/' }
    - { 标签: '/tags/' }
    - { 搜索: '/search/' }
  关于我:
    - '/about/'
    - { 关于: '/about/' }
    - { 豆瓣: 'https://www.douban.com/people/yisha7/'}
    - { Github: 'https://github.com/yifeitao'}
    - { Email: 'mailto:yifeitao@gmail.com'} 

# Add your friend-links
# friends:
#   A: 'link_A'
#   B: 'link_B'

# Relative path compatibility (JS hack, experimental and buggy feature)
# relative_path: true

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

# Comments provider config
comments_provider: vssue
owner: yifeitao
repo: yifeitao.github.io
vssue_clientId: 1d4ebc70fd877e40b5fa
vssue_clientSecret: 209ea95a15aa7c9ae6eae6abcdadc2200f7dedbe
#livere_uid: MTAyMC8zNDI2NS8xMDgwMg==
#disqus_shortname: yifeitao

# Analytics provider config
analytics_provider: google
google_analytics: UA-98784328-1

# reveal.js slide template
reveal_path: https://cdn.bootcss.com/reveal.js/3.4.1/

# additional message in sidebar
addition: '</br>朝闻道 夕死可矣'

# Reading Files
include:
  - .htaccess
  - _pages