# Site Info
title: "易飞滔Todd ｜ 次生进化"
slogan: "关注创造、学习与投资"
baseurl: ''
weburl: 'https://yifeitao.com'
author: 'yifeitao'
logo: '/assets/images/logo.png'

# Site configurations
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
recent_post: 10
permalink: '/:year//:month/:title'

# Navigation (2nd level links supported)
nav:
  次生进化:
    - '/'
    - { 归档: '/archive/' }
    - { 分类: '/categories/' }
    - { 标签: '/tags/' }
    - { 搜索: '/search/' }
    - { 关于: '/about/' }

# Add your friend-links
# friends:
#   A: 'link_A'
#   B: 'link_B'

# Relative path compatibility (JS hack, experimental and buggy feature)
# relative_path: true

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

# Comments provider config
comments_provider: utterances
owner: ifeitao
repo: ifeitao.github.io
#livere_uid: MTAyMC8zNDI2NS8xMDgwMg==
#disqus_shortname: yifeitao

# Analytics provider config
analytics_provider: google
google_analytics: G-NSGZR3ZT9N

# reveal.js slide template
reveal_path: https://cdn.jsdelivr.net/npm/reveal.js@3.7.0/

# additional message in sidebar
addition: '</br>念念不忘 必有回响'

# Reading Files
include:
  - .htaccess
  - _pages